version: '3.8'

services:
    db:
      image: postgres:15
      container_name: picpay_postgres
      restart: always
      environment:
        POSTGRES_DB: picpaydb
        POSTGRES_USER: picpay
        POSTGRES_PASSWORD: picpay123
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
